name: CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout develop
        uses: actions/checkout@v2

      - name: Set up Go version 1.17.5
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.5

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Test
        run: go test -race ./...

